name: CI

on:
  push:
    tags:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-2019, ubuntu-18.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          if [ "$RUNNER_OS" == "Windows" ]; then
            cl.exe //LD //Fe:default-enabled-lle-modules-file.dll plugin.cpp
          else
            g++ plugin.cpp -shared -o default-enabled-lle-modules-file.so -fPIC
          fi
      - name: Prepare to upload
        if: github.event_name == 'push'
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          export VERSION=${GITHUB_REF:10}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          if [ "$RUNNER_OS" == "Windows" ]; then
            7z a vvctre-plugin-default-enabled-lle-modules-file-$VERSION-${{runner.os}}.7z default-enabled-lle-modules-file.dll license.txt default-enabled-lle-modules.txt
          else
            7z a vvctre-plugin-default-enabled-lle-modules-file-$VERSION-${{runner.os}}.7z default-enabled-lle-modules-file.so license.txt default-enabled-lle-modules.txt
          fi
      - name: Upload to GitHub Releases
        if: github.event_name == 'push'
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          file: vvctre-plugin-default-enabled-lle-modules-file-${{env.VERSION}}-${{runner.os}}.7z
          asset_name: vvctre-plugin-default-enabled-lle-modules-file-${{env.VERSION}}-${{runner.os}}.7z
          tag: ${{github.ref}}
          overwrite: true
      - name: Upload artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v1
        with:
          name: vvctre-plugin-default-enabled-lle-modules-file-${{runner.os}}
          path: .
